### PR TITLE
add fantom to explorer

### PR DESCRIPTION
**Pull request by justinschuldt**
adding a new chain to Explorer requires:
- add the contract addresses to the `.env` files
- add the chain to the explorer utils (name, id, env var names)
- add the explorer URL
- add a `ChainOverviewCard` to `ExplorerStats`
- add a color to `chainColors` represent the chain on chats & graphs
- add the chain's logo as an SVG file, and add it to `ChainIcon.tsx`

---
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/935)

### CODE REVIEW

**Review by ckeun — DISMISSED** [review]
thanks for putting this together! next chain's on us! ;)

**Review by evan-gray — CHANGES_REQUESTED** [review]
Couple small display issues :slightly_smiling_face: 

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/935#-:-MxKviN445Al-pEsCM0O:bymp1ae)* status: all files reviewed, 2 unresolved discussions (waiting on @justinschuldt and @kev1n-peters)

___
*[explorer/src/components/ExplorerStats/ChainOverviewCard.tsx, line 65 at r1](https://reviewable.io/reviews/certusone/wormhole/935#-MxKujRC5yHCKl8Xhnvq:-MxKujRC5yHCKl8Xhnvr:b-qbpb5b) ([raw file](https://github.com/certusone/wormhole/blob/211739de984afc04211d8e0ba0b27e368b4d98da/explorer/src/components/ExplorerStats/ChainOverviewCard.tsx#L65)):*
> ```XML
>     !("*" in notionalTransferredToCumulative.AllTime[dataKey])
>   ) {
>     return <>coming soon</>
> ```

The styling of this doesn't match the other "Sent"s. Also something is causing the name to be missing

___
*[explorer/src/utils/consts.ts, line 59 at r1](https://reviewable.io/reviews/certusone/wormhole/935#-MxKvSml5bi91fxBv9TM:-MxKvSml5bi91fxBv9TN:b3tslmq) ([raw file](https://github.com/certusone/wormhole/blob/211739de984afc04211d8e0ba0b27e368b4d98da/explorer/src/utils/consts.ts#L59)):*
> ```XML
>   Avalanche,
>   Oasis,
>   Fantom
> ```

Perhaps this is why the chain doesn't show up because this would make Fantom = 8? You can add in all the other placeholder chains here

**Comment by justinschuldt** [comment]
___
*[explorer/src/components/ExplorerStats/ChainOverviewCard.tsx, line 65 at r1](https://reviewable.io/reviews/certusone/wormhole/935#-MxKujRC5yHCKl8Xhnvq:-MxL2gwVD0nX_9g_s2Zt:b-gucrk8) ([raw file](https://github.com/certusone/wormhole/blob/211739de984afc04211d8e0ba0b27e368b4d98da/explorer/src/components/ExplorerStats/ChainOverviewCard.tsx#L65)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

The styling of this doesn't match the other "Sent"s. Also something is causing the name to be missing


</blockquote></details>

The text in the screenshot is here https://github.com/certusone/wormhole/blob/dev.v2/explorer/src/components/ExplorerStats/ChainOverviewCard.tsx#L109, is not changed by this PR. Agree it would be good to update the styling there.

**Comment by justinschuldt** [comment]
___
*[explorer/src/utils/consts.ts, line 59 at r1](https://reviewable.io/reviews/certusone/wormhole/935#-MxKvSml5bi91fxBv9TM:-MxL3KtM2ZUeSYfHDHAo:b-75crd0) ([raw file](https://github.com/certusone/wormhole/blob/211739de984afc04211d8e0ba0b27e368b4d98da/explorer/src/utils/consts.ts#L59)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

Perhaps this is why the chain doesn't show up because this would make Fantom = 8? You can add in all the other placeholder chains here
</blockquote></details>

Good catch, updated. Might make sense to just add the chains that are already in the guardian and SDK to explorer, preemptively, where the "ChainOverviewCard" won't show until stats are returning, like this PR does for Fantom.

**Review by kev1n-peters — APPROVED** [review]

**Review by evan-gray — APPROVED** [review]
Added a couple small fixes, all the chains were showing up on the 7 day and the type check was upset. Aligned the styles while there.

> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/935#-:-MxlObU544vsMZopmhM5:b-sh685g)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @justinschuldt)

___
*[explorer/src/components/ExplorerStats/ChainOverviewCard.tsx, line 65 at r1](https://reviewable.io/reviews/certusone/wormhole/935#-MxKujRC5yHCKl8Xhnvq:-MxlIgrgD5hc-5zzIqq5:bb6mt9b) ([raw file](https://github.com/certusone/wormhole/blob/211739de984afc04211d8e0ba0b27e368b4d98da/explorer/src/components/ExplorerStats/ChainOverviewCard.tsx#L65)):*
<details><summary><i>Previously, justinschuldt (Justin Schuldt) wrote…</i></summary><blockquote>

The text in the screenshot is here https://github.com/certusone/wormhole/blob/dev.v2/explorer/src/components/ExplorerStats/ChainOverviewCard.tsx#L109, is not changed by this PR. Agree it would be good to update the styling there. 
</blockquote></details>

:+1:

**Review by evan-gray — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/935)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @justinschuldt)

**Review by evan-gray — APPROVED** [review]
Fixed a couple small things, one with the 7 day displaying all chains, another with the type check for ChainIDs. Aligned the styles while in the area.

> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/935#-:-MxlPT5y-WSB0ntWkkNQ:b-e7mq78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @justinschuldt)

**Comment by evan-gray** [comment]
Fixed a couple small things, one with the 7 day displaying all chains, another with the type check for ChainIDs. Aligned the styles while in the area.

**Review by ckeun — APPROVED** [review]

**Pull request merged**
