### PR TITLE
explorer animations & fixes

### PR DESCRIPTION
**Pull request by timpau**
All pages
	Animations:	
		- gradients
		- header swirls
		- side swirls
		- content rows
		- icons on “Cross-chain everything”
Brand Page
	- copy change
	- removed redundant info
Apps page
	
	- fix Allas Dex copy and icon

---
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/1009)

### CODE REVIEW

**Review by evan-gray — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/1009)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @timpau)

**Review by kev1n-peters — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/1009)* status: all files reviewed, 1 unresolved discussion (waiting on @timpau)

___
*[explorer/src/components/Footer.tsx, line 55 at r1](https://reviewable.io/reviews/certusone/wormhole/1009#-MyJbJlw6iTbYUUdy-a0:-MyJbJlw6iTbYUUdy-a1:b-z5p0be) ([raw file](https://github.com/certusone/wormhole/blob/99e06b2bbe362edaa5650d2eeb1e93f9843f306b/explorer/src/components/Footer.tsx#L55)):*
> ```XML
> 
>     var viewportWidth = window.innerWidth || document.documentElement.clientWidth;
>     if (viewportWidth > 768) {
> ```

When the viewport width is <= 768 it looks like the footer image is shifted, here's an example: 

Can we make it so the image is centered or something?

**Comment by timpau** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/certusone/wormhole/1009)_ status: all files reviewed, 1 unresolved discussion (waiting on @timpau)
> 
> _[explorer/src/components/Footer.tsx, line 55 at r1](https://reviewable.io/reviews/certusone/wormhole/1009#-MyJbJlw6iTbYUUdy-a0:-MyJbJlw6iTbYUUdy-a1:b-z5p0be) ([raw file](https://github.com/certusone/wormhole/blob/99e06b2bbe362edaa5650d2eeb1e93f9843f306b/explorer/src/components/Footer.tsx#L55)):_
> 
> > ```
> >     var viewportWidth = window.innerWidth || document.documentElement.clientWidth;
> >     if (viewportWidth > 768) {
> > ```
> 
> When the viewport width is <= 768 it looks like the footer image is shifted, here's an example:  Can we make it so the image is centered or something?

yes, i will fix it asap

**Review by kev1n-peters — APPROVED** [review]

**Review by evan-gray — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> Dismissed @kev1n-peters from a discussion.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/1009)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @evan-gray and @kev1n-peters)

**Review by evan-gray — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/1009#-:-MyJu47CDWNJzDRdkkHm:bnfp4nl)* status: 4 of 10 files reviewed, all discussions resolved (waiting on @evan-gray)

**Pull request merged**
