### PR TITLE
Terra: Fixed guardian set expiration and quorum logic, tests updated

### LINKED ISSUE #143: terra: guardian set expiration is mishandled
[Kudelski audit finding for the Everstake Terra audit]

guardian set expire dates seem to be "inverted", i.e. they will give an error for the current guardian set or an old guardian set which has not expired, but will work with guardian sets which has expired. This only works in the unit test because a guardian set that has expired is actually used.

```
    if guardian_set.expiration_time == 0 || guardian_set.expiration_time > env.block.time {
        return ContractError::GuardianSetExpired.std_err();
    }
 ```

### PR DESCRIPTION
**Pull request by ysavchenko**
Fixes #143 and #144 
Also updated tests to cover those issues.
And moved VAA hash storage to the end of processing (#142).

Upd:
Additional changes:
- added new descriptive errors in terra wormhole contract 
- 0-expiration guardian sets error fixed 
- added script for test VAAs generation 
- added full test coverage for the VAA processing in the contract 
- fixed cargo clippy/fmt warnings

Upd2:
- tests for lock assets
- test for asset registration callback
- tests for set active
- test for guardian set query

Upd3:
- Terra integrated to the e2e tests

---
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/145)

### CODE REVIEW

**Review by leoluk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/145#-:-MOl2zw26W_3KUfwKog9:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @leoluk and @ysavchenko)

___
*[terra/contracts/wormhole/src/contract.rs, line 189 at r1](https://reviewable.io/reviews/certusone/wormhole/145#-MOl3HhM-5J3-iML00qv:-MOl3HhM-5J3-iML00qw:b771w35) ([raw file](https://github.com/certusone/wormhole/blob/a1a1fbc0c203c44eddddce0161d85205039efa0d/terra/contracts/wormhole/src/contract.rs#L189)):*
> ```Rust
>     };
> 
>     if result.is_ok() {
> ```

Is there any situation where result is non-OK, but state has been altered and the tx is not reverted?

**Review by ysavchenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/145)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @leoluk)

___
*[terra/contracts/wormhole/src/contract.rs, line 189 at r1](https://reviewable.io/reviews/certusone/wormhole/145#-MOl3HhM-5J3-iML00qv:-MOlRl0h6VfLweIntMvG:b-h7fasp) ([raw file](https://github.com/certusone/wormhole/blob/a1a1fbc0c203c44eddddce0161d85205039efa0d/terra/contracts/wormhole/src/contract.rs#L189)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Is there any situation where result is non-OK, but state has been altered and the tx is not reverted?
</blockquote></details>

No, if result is Err transaction is always reverted.

**Review by ysavchenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/145)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @leoluk)

___
*[terra/contracts/wormhole/src/contract.rs, line 189 at r1](https://reviewable.io/reviews/certusone/wormhole/145#-MOl3HhM-5J3-iML00qv:-MPAN9Uc-Vbiv9S5SEvp:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/a1a1fbc0c203c44eddddce0161d85205039efa0d/terra/contracts/wormhole/src/contract.rs#L189)):*
<details><summary><i>Previously, ysavchenko (Yuriy Savchenko) wrote…</i></summary><blockquote>

No, if result is Err transaction is always reverted.
</blockquote></details>

Done.

**Comment by hendrikhofstadt** [comment]
Expirity looks broken. A expirity of 0 should inidcate "never expires". This is used for the currently active guardian set (which should never expire). Once it is replaced, the old guardianset should expire after the specified time while the new one should be active forever (or until replaced)

**Comment by ysavchenko** [comment]
> Expiration logic looks broken. A expiry time of 0 should indicate "never expires". This is used for the currently active guardian set (which should never expire). Once it is replaced, the old guardianset should expire after the specified time while the new one should be active forever (or until replaced)

It is one of the things fixed in this PR. The fixed logic is to throw error in case:
https://github.com/everstake/wormhole/blob/31fc5451e2464cf324e5621366fe242e6043f051/terra/contracts/wormhole/src/contract.rs#L149
So only if expiration is non-zero AND it is in the past.

**Review by leoluk — APPROVED** [review]
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/145)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by leoluk — APPROVED** [review]
Awesome test coverage - merging with the usual caveat about the CosmWasm contract.

> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/145#-:-MRQKbn1D9Nz36lrhFNl:b-ogv47p)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
