### PR TITLE
bridge_ui: Added tags for SEO

### PR DESCRIPTION
**Pull request by kev1n-peters**
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/979)

### CODE REVIEW

**Review by evan-gray — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/979)* status: all files reviewed, 2 unresolved discussions (waiting on @justinschuldt and @kev1n-peters)

___
*[bridge_ui/public/index.html, line 14 at r1](https://reviewable.io/reviews/certusone/wormhole/979#-MxgvrQWAITye9w_-Lx5:-MxgvrQWAITye9w_-Lx6:bxpvila) ([raw file](https://github.com/certusone/wormhole/blob/e1103bc8ffc4943dd11f7fe0b1f32735faeaf6e5/bridge_ui/public/index.html#L14)):*
> ```HTML
>     <meta property="og:title" content="Portal Token Bridge" />
>     <meta property="og:type" content="website" />
>     <meta property="og:url" content="https://www.portalbridge.com" />
> ```

nix `www.` :upside_down_face: 
___
*[bridge_ui/public/index.html, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/979#-Mxgvz0qAKbOUI_XQgvr:-Mxgvz0qAKbOUI_XQgvs:b-43ght8) ([raw file](https://github.com/certusone/wormhole/blob/e1103bc8ffc4943dd11f7fe0b1f32735faeaf6e5/bridge_ui/public/index.html#L17)):*
> ```HTML
>     <meta
>       property="og:image"
>       content="https://raw.githubusercontent.com/certusone/wormhole/dev.v2/explorer/src/images/wormhole.png"
> ```

1. Should an image be created for this?
2. Should that image be put in the static folder to be hosted with this site?

**Review by kev1n-peters — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/979)* status: all files reviewed, 2 unresolved discussions (waiting on @evan-gray, @justinschuldt, and @kev1n-peters)

___
*[bridge_ui/public/index.html, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/979#-Mxgvz0qAKbOUI_XQgvr:-Mxj5R1N53weehZBzzY5:b6eac6r) ([raw file](https://github.com/certusone/wormhole/blob/e1103bc8ffc4943dd11f7fe0b1f32735faeaf6e5/bridge_ui/public/index.html#L17)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

1. Should an image be created for this?
2. Should that image be put in the static folder to be hosted with this site?
</blockquote></details>

1. I'm not sure we need to create a new one, the one being used here is what explorer uses for this tag
2. We can copy this image into the public directory and set content="%PUBLIC_URL%/wormhole.png" I think

**Review by evan-gray — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/979)* status: all files reviewed, 2 unresolved discussions (waiting on @justinschuldt and @kev1n-peters)

___
*[bridge_ui/public/index.html, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/979#-Mxgvz0qAKbOUI_XQgvr:-MxjJOzW5v2N8qIUQwR7:brgb62n) ([raw file](https://github.com/certusone/wormhole/blob/e1103bc8ffc4943dd11f7fe0b1f32735faeaf6e5/bridge_ui/public/index.html#L17)):*
<details><summary><i>Previously, kev1n-peters wrote…</i></summary><blockquote>

1. I'm not sure we need to create a new one, the one being used here is what explorer uses for this tag
2. We can copy this image into the public directory and set content="%PUBLIC_URL%/wormhole.png" I think
</blockquote></details>

fair for now and concur

**Review by kev1n-peters — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/979)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @evan-gray and @justinschuldt)

___
*[bridge_ui/public/index.html, line 14 at r1](https://reviewable.io/reviews/certusone/wormhole/979#-MxgvrQWAITye9w_-Lx5:-MxjOFxADaZ7jExhlRi6:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/e1103bc8ffc4943dd11f7fe0b1f32735faeaf6e5/bridge_ui/public/index.html#L14)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

nix `www.` :upside_down_face: 
</blockquote></details>

Done.
___
*[bridge_ui/public/index.html, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/979#-Mxgvz0qAKbOUI_XQgvr:-MxjOGW_6EBUKkGBhJPi:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/e1103bc8ffc4943dd11f7fe0b1f32735faeaf6e5/bridge_ui/public/index.html#L17)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

fair for now and concur
</blockquote></details>

Done.

**Review by evan-gray — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/979)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @justinschuldt)

**Review by chase-45 — APPROVED** [review]

**Pull request merged**
