### PR TITLE
Fix guardian set initialization race condition

### LINKED ISSUE #184: Panic when an observation is received before gs init
```
guardiand[6053]: panic: runtime error: invalid memory address or nil pointer dereference
guardiand[6053]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xab0189]
guardiand[6053]: goroutine 29 [running]:
guardiand[6053]: github.com/certusone/wormhole/bridge/pkg/common.(*GuardianSet).KeyIndex(0x0, 0xbee1536940e9d740, 0x9b4f953990407fbf, 0xb3be6d5, 0x29b43e0, 0x20)
guardiand[6053]: #011/opt/worm/wormhole/bridge/pkg/common/guardianset.go:34 +0x29
guardiand[6053]: github.com/certusone/wormhole/bridge/pkg/processor.(*Processor).handleObservation(0xc0000f4380, 0x1b7b120, 0xc000688f00, 0xc0032b3110)
guardiand[6053]: #011/opt/worm/wormhole/bridge/pkg/processor/observation.go:134 +0x9a5
guardiand[6053]: github.com/certusone/wormhole/bridge/pkg/processor.(*Processor).Run(0xc0000f4380, 0x1b7b120, 0xc000688f00, 0x17626f8, 0xc000113480)
guardiand[6053]: #011/opt/worm/wormhole/bridge/pkg/processor/processor.go:162 +0x27a
guardiand[6053]: github.com/certusone/wormhole/bridge/pkg/supervisor.(*supervisor).processSchedule.func1(0xc000688c80, 0xc00006ddd0, 0xc0001851f0)
guardiand[6053]: #011/opt/worm/wormhole/bridge/pkg/supervisor/supervisor_processor.go:147 +0x6a
guardiand[6053]: created by github.com/certusone/wormhole/bridge/pkg/supervisor.(*supervisor).processSchedule
guardiand[6053]: #011/opt/worm/wormhole/bridge/pkg/supervisor/supervisor_processor.go:133 +0xae
systemd[1]: guardiand.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: guardiand.service: Failed with result 'exit-code'.
```

### PR DESCRIPTION
**Pull request by leoluk**
Fixes #184

---
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/191)

### CODE REVIEW

**Review by drozdziak1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/191)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hendrikhofstadt and @leoluk)

___
*[bridge/pkg/processor/observation.go, line 132 at r1](https://reviewable.io/reviews/certusone/wormhole/191#-MWP1gwsE7dWNqxvjXPV:-MWP1gwtBe081k2wMWje:btoccxy) ([raw file](https://github.com/certusone/wormhole/blob/c4e5b1c61e2824b8249635794374f5a22dcc6779/bridge/pkg/processor/observation.go#L132)):*
> ```Go
> 	}
> 
> 	// We haven't yet observed the trusted guardian set on Ethereum, and therefore, it's impossible to verify it.
> ```

How is this tied to Ethereum specifically?

**Review by drozdziak1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/191)* status: all files reviewed, 1 unresolved discussion (waiting on @hendrikhofstadt and @leoluk)

**Review by leoluk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/191)* status: all files reviewed, 1 unresolved discussion (waiting on @drozdziak1 and @hendrikhofstadt)

___
*[bridge/pkg/processor/observation.go, line 132 at r1](https://reviewable.io/reviews/certusone/wormhole/191#-MWP1gwsE7dWNqxvjXPV:-MWPLeX18E7ucNnpLx47:b3iuqh0) ([raw file](https://github.com/certusone/wormhole/blob/c4e5b1c61e2824b8249635794374f5a22dcc6779/bridge/pkg/processor/observation.go#L132)):*
<details><summary><i>Previously, drozdziak1 (Stanisław Drozd) wrote…</i></summary><blockquote>

How is this tied to Ethereum specifically?
</blockquote></details>

https://github.com/certusone/wormhole/blob/9c1d6ee00c2add7215d421e05b175e0b0330710a/bridge/pkg/ethereum/watcher.go#L140

**Review by drozdziak1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hendrikhofstadt)

**Review by drozdziak1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/191#-:-MWUB3P60ZO3Yuf0HXY4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hendrikhofstadt)

**Pull request merged**
