### PR TITLE
specify dependabot dirs

### PR DESCRIPTION
**Pull request by evan-gray**
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/859)

### CODE REVIEW

**Review by kev1n-peters — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/859)* status: all files reviewed, 1 unresolved discussion (waiting on @evan-gray)

___
*[.github/dependabot.yml, line 16 at r1](https://reviewable.io/reviews/certusone/wormhole/859#-Mw1vUH80JsSBj2DXbyR:-Mw1vUH80JsSBj2DXbyS:b6xwc4n) ([raw file](https://github.com/certusone/wormhole/blob/0c8b34bd1826aa4bac5fd5349059c9445fab37fb/.github/dependabot.yml#L16)):*
> ```YAML
>       - "bridge_ui"
>   - package-ecosystem: "npm"
>     directory: "/ethereum"
> ```

Should we exclude ethereum from the outset and maybe add it down the road?

**Comment by evan-gray** [comment]
___
*[.github/dependabot.yml, line 16 at r1](https://reviewable.io/reviews/certusone/wormhole/859#-Mw1vUH80JsSBj2DXbyR:-Mw1wwWX-bUiBXrHw9jW:bx99opq) ([raw file](https://github.com/certusone/wormhole/blob/0c8b34bd1826aa4bac5fd5349059c9445fab37fb/.github/dependabot.yml#L16)):*
<details><summary><i>Previously, kev1n-peters wrote…</i></summary><blockquote>

Should we exclude ethereum from the outset and maybe add it down the road?
</blockquote></details>

Sounds reasonable, will do.

**Comment by evan-gray** [comment]
also added more chill

**Review by leoluk — APPROVED** [review]

**Review by kev1n-peters — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/859)* status: all files reviewed, 1 unresolved discussion (waiting on @kev1n-peters)

**Review by kev1n-peters — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @evan-gray)

**Pull request merged**
