### PR TITLE
Terra key moved out from env variable, VAA submission on Terra made async

### LINKED ISSUE #96: terra: read terra fee payer secret from file like all other keys
Using TERRA_FEE_PAYER is inconsistent with p2p, Solana and bridge keys.

### PR DESCRIPTION
**Pull request by ysavchenko**
Resolves #96 , #95

---
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/129)

### CODE REVIEW

**Review by leoluk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/129)* status: all files reviewed, 4 unresolved discussions (waiting on @ysavchenko)

___
*[bridge/cmd/guardiand/bridge.go, line 320 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPCdul1y9Hwih2xUEu:-MNPCdul1y9Hwih2xUEv:bj4th3) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/cmd/guardiand/bridge.go#L320)):*
> ```Go
> 
> 	// Load Terra fee payer key
> 	var terraFeePayer *string
> ```

Why `*string`?
___
*[bridge/pkg/terra/sender.go, line 16 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPCxGK86dZ4hIR5Fy5:-MNPCxGK86dZ4hIR5Fy6:b-foonh1) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L16)):*
> ```Go
> )
> 
> const devnetFeePayerKey = "notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius"
> ```

Please move this constant to pkg/devnet where the other constants are.
___
*[bridge/pkg/terra/sender.go, line 93 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPDa0Z98clxvt4Bu8R:-MNPDa0Z98clxvt4Bu8S:bxf7rfc) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L93)):*
> ```Go
> 
> // ReadKey reads file and returns its content as a string
> func ReadKey(path string) (*string, error) {
> ```

Why *string? Just use a regular string and `return string(b), err`.
___
*[bridge/pkg/terra/sender.go, line 104 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPD6q19zKHba-ESk9A:-MNPD6q2EBrNAr4Xcc6X:b-hg0vve) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L104)):*
> ```Go
> // WriteDevnetKey writes default devnet key to the file
> func WriteDevnetKey(path string) {
> 	_ = ioutil.WriteFile(path, []byte(devnetFeePayerKey), 0644)
> ```

I think this error should be caught (panic is fine). And not that it matters for a devnet key, but best to change mode to 0600 to not scare auditors :-)

**Review by leoluk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/129)* status: all files reviewed, 4 unresolved discussions (waiting on @ysavchenko)

___
*[bridge/pkg/terra/sender.go, line 93 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPDa0Z98clxvt4Bu8R:-MNPECWtEvGXH_PF8eUH:bmefgui) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L93)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Why *string? Just use a regular string and `return string(b), err`.
</blockquote></details>

(err, `return string(b), nil`, of course)

**Review by ysavchenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/129)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @leoluk)

___
*[bridge/cmd/guardiand/bridge.go, line 320 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPCdul1y9Hwih2xUEu:-MNPMqlg6ao6yFemrSN8:b-spw3ih) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/cmd/guardiand/bridge.go#L320)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Why `*string`?
</blockquote></details>

Oh, because it was settings before and had type *string :). Fixing.
___
*[bridge/pkg/terra/sender.go, line 16 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPCxGK86dZ4hIR5Fy5:-MNPMxdh7mBQ5xbLbGhg:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L16)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Please move this constant to pkg/devnet where the other constants are.
</blockquote></details>

Done.
___
*[bridge/pkg/terra/sender.go, line 93 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPDa0Z98clxvt4Bu8R:-MNPNUpe5pgcsu2fyLuE:bb6un1j) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L93)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

(err, `return string(b), nil`, of course?
</blockquote></details>

Done
___
*[bridge/pkg/terra/sender.go, line 104 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPD6q19zKHba-ESk9A:-MNPNWMe34koga38v6Yt:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/pkg/terra/sender.go#L104)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

I think this error should be caught (panic is fine). And not that it matters for a devnet key, but best to change mode to 0600 to not scare auditors :-)
</blockquote></details>

Done.

**Review by ysavchenko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/129)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @leoluk)

___
*[bridge/cmd/guardiand/bridge.go, line 320 at r1](https://reviewable.io/reviews/certusone/wormhole/129#-MNPCdul1y9Hwih2xUEu:-MNPOMB841najWbv_41M:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/00e3191676b8b45c60881ce5c2c8356fa0ad06cf/bridge/cmd/guardiand/bridge.go#L320)):*
<details><summary><i>Previously, ysavchenko (Yuriy Savchenko) wrote…</i></summary><blockquote>

Oh, because it was settings before and had type *string :). Fixing.
</blockquote></details>

Done.

**Review by leoluk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/129)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
