### PR TITLE
Update dashboard with variables support  

### PR DESCRIPTION
**Pull request by vpoz-everstake**
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/322)

### CODE REVIEW

**Comment by leoluk** [comment]
We haven't upgraded to Grafana 8 yet - will take a look soon!

**Comment by vpoz-everstake** [comment]
Thanks, we're waiting)

**Comment by leoluk** [comment]
The changes appear to be for Wormhole v1, rather than v2.

**Comment by ank-everstake** [comment]
@leoluk Please merge this PR, apparently current dashboard lacks some metrics.
Ping us if it needs edit.

**Comment by leoluk** [comment]
Closing this PR - your changes will be incorporated when we update the dashboard :)

**Pull request closed without merging**
