### PR TITLE
enable additional linters, including gosec

### PR DESCRIPTION
**Pull request by tbjump**
This change is [Reviewable](https://reviewable.io/reviews/certusone/wormhole/1215)

### CODE REVIEW

**Comment by tbjump** [comment]
Depends on https://github.com/certusone/wormhole/pull/1127 to fix one of the gosec issues

**Review by claudijd — APPROVED** [review]
This as is, looks good.  However, I feel like we should address the gaps here such that the lint passes before merging or we're going to start failing PRs for folks unrelated to the code they are changing.

**Comment by SEJeff** [comment]
@claudijd thoughts on enabling it in warn only mode  first allowing us to slowly churn through the comments? Iteration is best for this sort of thing. When they’re all addressed, we can make it a hard fail.

**Comment by tbjump** [comment]
> This as is, looks good. However, I feel like we should address the gaps here such that the lint passes before merging or we're going to start failing PRs for folks unrelated to the code they are changing.

Once my other PRs are merged and I rebase, all gosec issues should be fixed. Can't merge this one before fixing them anyways.

**Review by SEJeff — APPROVED** [review]

**Review by claudijd — DISMISSED** [review]

**Review by SEJeff — APPROVED** [review]

**Review by claudijd — APPROVED** [review]

**Pull request merged**
